### ISSUE TITLE
OG 태그 변경

### ISSUE THREAD

**Issue by jisungbin** [duckie-team/duckie-opensource#3]
`og:description` -> "덕키는 모든 제품을 오픈소스로 공개합니다." (현스님 입맛에 따라 수정 가능)
`og:image` -> 현스님 디자인 파이팅!

**Comment by HyunsDev** [comment]
![image](https://user-images.githubusercontent.com/46562466/200131475-49b1154b-d956-4037-b75b-ed9134edfbd2.png)
og 이미지는 이거 재탕하겠습니다 ㅋㅋㅋ

**Comment by jisungbin** [comment]
## DONE

https://github.com/duckie-team/duckie-opensource/commit/dfb0be523af107ea5a1b4dcc43058b277a765740
